### ISSUE TITLE
empty tables on new install

### ISSUE THREAD

**Issue by hrwebasst** [RNGR/Directus#1002]
Fresh install, tried to install by itself along side a database with the same user also tried installing inside of a pre-existing database and both ways shows empty tables. Where do I point to the database I want to show?

![screenshot101](https://cloud.githubusercontent.com/assets/9060082/9641453/99a59410-516b-11e5-9090-e9215a7a8f87.png)

**Comment by WellingGuzman** [comment]
@hrwebasst yeah it's not well documented yet, but when a table is not created by Directus, all users groups doesn't have any permission to it, for example can view those tables.

To see those tables you have to go to Settings (gear at the bottom of the sidebar) > Groups Permission > and pick a group and you should see all the tables there and you can change all those permissions by clicking the icons next to the table's name.

Let me know if that works for you.

**Comment by hrwebasst** [comment]
@WellingGuzman Odd... I'm baking this into our internal docker infrastructure for development and trying to programatically set everything up. Maybe Directus isn't quite ready for this, queries fail off the bat too after doing this. 
![screenshot102](https://cloud.githubusercontent.com/assets/9060082/9641850/b451b170-516d-11e5-9f80-d71bd5368293.png)
But at least the tables are showing up now, I'll try to find this logic and make it happen by default to see if I can migrate from phpmyadmin in future, thank you.

**Comment by WellingGuzman** [comment]
Thanks @hrwebasst I'd take a look into it, but if you manage to solve this issue, let us know and we'll thank you.

**Comment by hrwebasst** [comment]
I assume this will be automatically fixed when someone deals with #982 

When I have some free time I'll look into it too.
