### ISSUE TITLE
How to change thumbnails size

### ISSUE THREAD

**Issue by Roakart** [RNGR/Directus#1027]
Hi !
I have searched for a long time and I did not find out how to change thumbnails size.
Can you help me.

Thanks

**Comment by benhaynes** [comment]
The thumbnail generated is one optimized (dimensions/quality/filesize) for the CMS itself. I assume you are looking for thumbnails to be used by your application? In version 5 there was an auto thumb generator for application use, but it was removed. We've used external scripts that check for a thumbs existence and if present it's returned... if not, it's generated (based on parameters) and returned.

I'll add a ticket (https://github.com/RNGR/Directus/issues/1028) to address this, thanks for the reminder!

**Comment by Roakart** [comment]
Yes I am.
I would like to change thumbnails size on my website without modify their quality, but the size of the thumbnail is 200px so I cannot.

**Comment by benhaynes** [comment]
Makes sense – we'll try to expedite that feature (https://github.com/RNGR/Directus/issues/1028), but are in the middle of some big schema tickets that came up during our last marketing push. In the meantime I would recommend looking into an external (on-the-fly) thumb generator. We appreciate your feedback, if I can dig up the script we use (outside of Directus) I'll send it over...

**Comment by Roakart** [comment]
Thanks ;)
