### ISSUE TITLE
Server error occurred! on login

### ISSUE THREAD

**Issue by sonyarianto** [RNGR/Directus#1038]
Sorry ask this again since I can't find good answer for this. I am trying install Directus on my VPS CentOS 6.5 using virtualmin, everything OK during installation and all requirements are OK, but when I login I got "Server error occured".
I checked on log and found below:
```
....htaccess: Option FollowSymlinks not allowed here....
```
how to make it work? I already follow to add overrideAllow All but it failed.

**Comment by benhaynes** [comment]
@WellingGuzman any thoughts on this?

**Comment by WellingGuzman** [comment]
@sonyarianto Apologies for a late response, but some hosting service do not allow `FollowSymlinks` option for security reason, and can expose other users files/directory.

A solution to this is using `SymLinksIfOwnerMatch` instead which only will follow the directory if the owner are the same.

So try to change `FollowSymlinks` with `SymLinksIfOwnerMatch` and see if it helps.

We are probably going to change it as well.

**Comment by sonyarianto** [comment]
No problem, but for beginner user will have difficulties if there is "advanced" requirement like this and will reduced the adoption of Directus to wider audiences. I imagine Diretus should be simple (think like Adminer) but with current feature, so everybody can install/deploy easily in any server (shared hosting, VPS, dedicated etc etc).

**Comment by WellingGuzman** [comment]
@sonyarianto Thank you very much for you suggestion, but to be honest we're not aware that some hosting forbid this option, now we are going to discuss the idea of changing `FollowSymlinks` with `SymLinksIfOwnerMatch` by default.
