### ISSUE TITLE
Blocking Error when trying to update my group profile

### ISSUE THREAD

**Issue by Mahjouba91** [RNGR/Directus#1042]
Hi,

I'm the owner of the website, I installed Directus with sample data and it works well.

I got an error when I'm trying to update my group profile. First, this field was blank, So I decided to put it in "Administrator" Group. But it fails, it says that I didn't chose any group. By the way, when I am trying to leave it blank, it fails too.

![users](https://cloud.githubusercontent.com/assets/8670083/10098859/d2d7dccc-6384-11e5-9c36-0eeaab0ab8f2.png)

**Comment by WellingGuzman** [comment]
Thanks @Mahjouba91 I'm taking care of this issue right now.
