### ISSUE TITLE
Every api call redirected to /api/api.php?run_api_router=1

### ISSUE THREAD

**Issue by DionTimmermann** [RNGR/Directus#1044]
I have a fresh install and successfully set up the DB. When trying to log in, I get the message "Server error occurred!".

mod_rewrite is enabled. It seems as if every api call (e.g.  www.myserver.com/path/to/directus/api/1/auth/login ) gets redirected to www.myserver.com/path/to/directus/api/api.php?run_api_router=1 , which then shows a 404 error. I had to remove the line "Options +FollowSymlinks" from the api/.htaccess, as on my server this is enabled by default and can not be overwritten. Since that change, however, I do not get any apache errors, just the 404 for every api call.

**Comment by benhaynes** [comment]
Hey @DionTimmermann – we're checking this out and will report back with a fix shortly. Thanks for bringing this to our attention!

**Comment by WellingGuzman** [comment]
@DionTimmermann we switched to `SymLinksIfOwnerMatch` this probably should've fixed your issue. 

@benhaynes Although I was thinking to delete this whole line anyways, but maybe not. I'm closing this issue.
