### ISSUE TITLE
Add new user group Call to action button doesn't work

### ISSUE THREAD

**Issue by Mahjouba91** [RNGR/Directus#1046]
In the URL path : www.mywebsite.com/settings/permissions

When I click on the call to action button "Add new user group", nothing happen whereas when I click on the green "+" button, it works.

**Comment by WellingGuzman** [comment]
@Mahjouba91 We are aware that this button is not working, but I think we thought on removing it. @benhaynes do you remember what was the final decision on this button?

**Comment by benhaynes** [comment]
@WellingGuzman – Let's keep the top (green) button in the header. We can remove the lower one. Then we can come up with a better admin system for when we need two primary buttons (edit fields page).
