### ISSUE TITLE
Uncaught exception on installation

### ISSUE THREAD

**Issue by zetalevel** [RNGR/Directus#1062]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'zsaint'@'localhost' (using password: YES)' in /opt/lampp/htdocs/Directus-build/api/vendor/zendframework/zend-db/Zend/Db/Adapter/Driver/Pdo/Connection.php:281 Stack trace: #0 /opt/lampp/htdocs/Directus-build/api/vendor/zendframework/zend-db/Zend/Db/Adapter/Driver/Pdo/Connection.php(281): PDO->__construct('mysql:dbname=sa...', 'zsaint', 'ghm', Array) #1 /opt/lampp/htdocs/Directus-build/api/vendor/zendframework/zend-db/Zend/Db/Adapter/Driver/Pdo/Pdo.php(244): Zend\Db\Adapter\Driver\Pdo\Connection->connect() #2 /opt/lampp/htdocs/Directus-build/api/vendor/zendframework/zend-db/Zend/Db/Sql/Sql.php(120): Zend\Db\Adapter\Driver\Pdo\Pdo->createStatement() #3 /opt/lampp/htdocs/Directus-build/api/vendor/zendframework/zend-db/Zend/Db/TableGateway/AbstractTableGateway.php(232): Zend\Db\Sql\Sql->prepareStatementForSqlObject(Object(Zend\Db\Sql\Select)) #4 /opt/lampp/htdocs/Directus-build/api/core/Directus/Db/TableGateway/AclAwareTable in /opt/lampp/htdocs/Directus-build/api/vendor/zendframework/zend-db/Zend/Db/Adapter/Driver/Pdo/Connection.php on line 289

**Comment by WellingGuzman** [comment]
Thanks @zetalevel I'm going to work on this.

**Comment by WellingGuzman** [comment]
Hey @zetalevel to make everything sure that this is not happen could also tell me what did you do to this to happen?

**Comment by WellingGuzman** [comment]
Still can't replicate this issue, maybe it was the `build` branch, I'd make sure to keep build up to date, and try it again, if not, we should closed until it happens again. what do you think @benhaynes ?

**Comment by benhaynes** [comment]
Yeah, let's get the dev branch merged into master and get the build up to date. We can close this ticket and reopen if it happens again.
