### ISSUE TITLE
Problem reordering on Listing view (happened on second reorder)

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#1076]
In the demo schema, when reordering items on the listing page (offices) – I'm getting the following error:

![screen shot 2015-11-12 at 11 57 38 pm](https://cloud.githubusercontent.com/assets/522079/11139113/3f30d4ac-8999-11e5-87aa-2e078e229ee1.png)

**Comment by benhaynes** [comment]
If you turn on reordering and drag the first item it works. Any items you drag after that throw an error. If you toggle the reorder off then on, it works the first time again.

**Comment by WellingGuzman** [comment]
Fixed in d36ead5234e378f4189a66cc3c757521ae4c5413
