### ISSUE TITLE
Adding a new relational column doesn't insert all needed parameters

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#481]
If you add a relational column to a table, some parameters are not saved. For example:

Adding a *test_image* SINGLE_FILE UI under arts:
http://directus.rngr.org/settings/tables/arts

Works, except its *directus_columns* record is missing the following:
* **relationship_type** – should have "MANYTOONE"
* **table_related** – should have "directus_files"
* **junction_key_right** – should have "test_image"

Since it is missing those values, the column does not get the relational icon/overlay (which now works) – so you have to add everything in the database directly.

It seems like the best way to handle this might be to have each UI file have variables for if it is relational, and any applicable defaults. For instance a SINGLE_FILE will always be MANYTOONE and should have a default related table of *directus_files*.

**Comment by WellingGuzman** [comment]
Does this still an Issue? I think I worked on this before.

**Comment by benhaynes** [comment]
@WellingGuzman I'm getting an error trying to add a field (it adds the field but no record into "directus_columns"). I can add the field, but when I go to save the table settings I get:

```
<error>
underscore.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:768 <error>underscore.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:768 _.extendunderscore.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:813 _.cloneColumnModel.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:80 module.exports.Backbone.Model.extend.toJSONbackbone.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:1148 Backbone.syncmain.js:337 Backbone.syncbackbone.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:289 _.extend.syncbackbone.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:492 _.extend.saveTablesView.js?bust=921658263a6766b1d8d5fce6c6be45b28bab7381:617 SettingsTables.Views.Table.BasePageView.extend.saveColumnsjquery-1.11.0.js:4624 n.event.dispatchjquery-1.11.0.js:4292 r.handle
```

**Comment by WellingGuzman** [comment]
@benhaynes I'm not getting any error, can you give a step by step on this one, and which table are you using?
Is this happening on the development server?

**Comment by benhaynes** [comment]
@WellingGuzman Probably a similar issue here: https://github.com/RNGR/directus6/issues/645

**Comment by WellingGuzman** [comment]
This was solved, does this still happening to you @benhaynes ?

**Comment by benhaynes** [comment]
Nope – this looks like it's solved! Thanks @WellingGuzman
