### ISSUE TITLE
DB/Schema Changes

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#565]
Are we, or can we, track all schema changes for Directus in some way? I am updating a few installs on my side and they are throwing some SQL errors – seemingly because of fields added/changed (see below). Do you have any thoughts around this?

Here is a SQL error I am getting on a dev install of Directus after upgrading to the newest version. It happens on any edit page with images on it:

Server Error – Unknown column 'sort' in 'order clause'
This query failed: SELECT `directus_files`.`id` AS `id`, `directus_files`.`active` AS `active`, `directus_files`.`name` AS `name`, `directus_files`.`url` AS `url`, `directus_files`.`title` AS `title`, `directus_files`.`location` AS `location`, `directus_files`.`caption` AS `caption`, `directus_files`.`type` AS `type`, `directus_files`.`charset` AS `charset`, `directus_files`.`tags` AS `tags`, `directus_files`.`width` AS `width`, `directus_files`.`height` AS `height`, `directus_files`.`size` AS `size`, `directus_files`.`embed_id` AS `embed_id`, `directus_files`.`user` AS `user`, `directus_files`.`date_uploaded` AS `date_uploaded`, `directus_files`.`storage_adapter` AS `storage_adapter`, `directus_files`.`needs_index` AS `needs_index` FROM `directus_files` WHERE `directus_files`.`active` IN ('1', '2') AND (-1 = '-1' OR `directus_files`.`id` = '-1') GROUP BY `directus_files`.`id` ORDER BY `sort` ASC LIMIT 100 OFFSET 0

**Comment by benhaynes** [comment]
@WellingGuzman It's odd, I am actually not seeing this on my local instance of Directus – only when I upgraded a client's version to the development branch. So my only thought is something changed in the DB schema or in the settings saved in the database.

**Comment by WellingGuzman** [comment]
I was thinking about how could be a best or better way to handle this, every time there were a change in the DB Schema, that new thing was missing and throwing error, one way that pop out of my head right now are, db updating files. But I'd try them out first and let you know how it ends up.

**Comment by WellingGuzman** [comment]
So I was looking on how to keep track to the DB Schema and really good solutions it's to use Migrations.
I found on alternative for PHP called [Ruckusing](https://github.com/ruckus/ruckusing-migrations). I haven't tested yet, but I would do it later but I have used migrations in Ruby and it does do the job, so this is the idea we need to implement.

**Comment by benhaynes** [comment]
Perfect! Once the current "urgent" bugs are resolved let's do this. **Ruckusing** it is!

**Comment by benhaynes** [comment]
@WellingGuzman Should we leave this issue open until things are further along or is this first pass looking pretty good?

**Comment by WellingGuzman** [comment]
@benhaynes this first implementation it's looking pretty great, I haven't had any issue so far.

I believe we should close this issue? any thoughts?

**Comment by benhaynes** [comment]
Excellent! Closing...
