### ISSUE TITLE
Adding a new onetomany column needs double action

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/Directus#645]
Adding a new one to many column would add the column first on the table, but it would be needed to click save on the table in order to insert the `directus_columns` info.

This happen to any _onetomany_ including _single file_.

**Comment by benhaynes** [comment]
@WellingGuzman – I feel like this is related to:
https://github.com/RNGR/directus6/issues/481

**Comment by benhaynes** [comment]
@WellingGuzman I added a ONETOMANY and after trying to use it I get:

```Server Error
Required column/ui metadata columns on table capabilities lack values: table_related junction_key_right```

directus_columns doesn't have a junction_key_right saved, so maybe it's not completely saving?

**Comment by WellingGuzman** [comment]
@benhaynes this also was fixed already. Does this still happening to you?

**Comment by benhaynes** [comment]
I haven't been seeing it – I will close and reopen if it occurs again. Thanks!
