### ISSUE TITLE
Removing bookmarks throws an error

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#703]
Clicking the "X" next to the bookmark throws a permission error. You should always have permission to remove bookmarks.

![screen shot 2015-03-13 at 9 21 27 am](https://cloud.githubusercontent.com/assets/522079/6639046/7c32ea2c-c962-11e4-8e6c-f58dd60d98c7.png)

![screen shot 2015-03-13 at 9 21 35 am](https://cloud.githubusercontent.com/assets/522079/6639050/7fdde3ca-c962-11e4-92e8-a033a312ff04.png)

**Comment by WellingGuzman** [comment]
@benhaynes deleting (soft/hard) it's always granted no matter what, admin only?

**Comment by benhaynes** [comment]
@WellingGuzman It seems that I still can't delete my bookmark, but the error shown above has stopped.

**Comment by benhaynes** [comment]
@WellingGuzman Odd, it was only the old Bookmark that I couldn't delete... it seems to be working now. Is there a way to highlight that Bookmark item in the sidebar? Currently it highlights the table it's on...
