### ISSUE TITLE
Review the possibility of using Vagrant for installs

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#713]
"Consider better installation/provisioning instructions? Wagtail uses vagrant for it's "demo" package: https://github.com/torchbox/wagtaildemo. It's a pretty amazing option to be able to run something like "vagrant up" in their repo directory and in a reasonably short amount of time have a demo app running. Your installation page on github scares me just a little bit..."

@WellingGuzman Let's discuss this and see if it might be a viable install method.

**Comment by benhaynes** [comment]
@WellingGuzman what's the status of this now that we have an initial version? Can we write up a Wiki (can be "Draft" if you want) for this and CLI?

**Comment by WellingGuzman** [comment]
This has been implemented: [1.3 Vagrant box [DRAFT]](https://github.com/RNGR/Directus/wiki/1.3-Vagrant-box-%5BDRAFT%5D)

I'll close it.
