### ISSUE TITLE
Composer dependencies help url does not resolve properly

### ISSUE THREAD

**Issue by jwdeitch** [RNGR/Directus#715]
install/install.php:272 - "https://github.com/RNGR/directus6/wiki/Installation-Guides#how-to-install-composer-dependencies" does not properly resolve - ends up at wiki home page. Maybe there should be a ```cd /api && composer install``` instruction in the install instructions :). (public wiki editing is restricted)

**Comment by benhaynes** [comment]
Ahh! Good catch, we changed the repo name from "directus6" to "directus" yesterday. Must have missed this. Updating now.

**Comment by benhaynes** [comment]
@jwdeitch These links have been updated and should be resolving now. Thanks again for catching this. Also, I've made the Wiki available for editing by the public, so feel free to adjust anything you see as being incorrect.
