### ISSUE TITLE
Email Messages should not be required when creating a new user

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#717]
Currently this checkbox (Email Messages) requires you to check it to add a user. It shouldn't.

**Comment by benhaynes** [comment]
@WellingGuzman I'm not sure why this is showing up as required, it isn't in the fixed schema. Maybe it's being rendered incorrectly?

**/app/schema/fixed/users.js**:210
```
{
            "id":"email_messages",
            "column_name":"email_messages",
            "type":"TINYINT",
            "is_nullable":"NO",
            "default_value":"1",
            "comment":"CMS messages will also be sent to email address above",
            "sort":6,
            "system":false,
            "master":false,
            "hidden_list":false,
            "hidden_input":false,
            "required":false,
            "ui":"checkbox"
          }
```

**Comment by benhaynes** [comment]
@WellingGuzman Great! Should the schema be updated too? Currently that column is ALLOW NULL...

**Comment by benhaynes** [comment]
Though – just tested and this seems to be working!

**Comment by WellingGuzman** [comment]
@benhaynes you right, we should do that, but before I did all the we need to talk about how this is all going to be handle so we do not need to do twice the work. editing the value twice.

**Comment by benhaynes** [comment]
@WellingGuzman sounds good. Let me know the options as you see them and we can figure out what's best.
