### ISSUE TITLE
404 on login

### ISSUE THREAD

**Issue by emcniece** [RNGR/Directus#721]
Fresh install and can't log in!

`POST http://45.55.153.182/api/1/auth/login 404 (Not Found)`

IP is accessible from outside and I can provide root if needed. What details can I provide?

**Comment by muddylemon** [comment]
Make sure you have rewrite installed and turned on for apache AND set *AllowOverride All* in your virtual host directive to use the .htaccess file in the site root..

**Comment by emcniece** [comment]
That's the ticket!! Thank you so much. 

This is a Ubuntu LAMP DO drop - had to edit /etc/apache2/apache2.conf under the /var/www section.
