### ISSUE TITLE
When viewing a File detail page, sidebar should highlight Files nav item

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#723]
When viewing detail pages (such as File Detail) the sidebar should reflect the parent item.

![screen shot 2015-03-17 at 11 23 08 pm](https://cloud.githubusercontent.com/assets/522079/6702126/fc52d88c-ccfc-11e4-8a7f-75a551c59009.png)

**Comment by WellingGuzman** [comment]
@benhaynes **NOTE**: This also happen with any nav item under System.

**Comment by benhaynes** [comment]
Lookin' good!
