### ISSUE TITLE
php_value in htaccess throws 500 if server doesn't allow

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#724]
".htaccess - the php_value lines at the bottom throw http 500's if the server doesn't allow them"

This came from a user today – can we look into this having an appropriate notification? Or is this working as expected?

**Comment by WellingGuzman** [comment]
I found a scenario when this is happening, `php_value` is only available on `mod_php`. Resulting in a 500 error page in other PHP mode setup.

[PR#725](https://github.com/RNGR/Directus/issues/725)

**Comment by benhaynes** [comment]
Excellent. We'll close this unless we hear it happening again. Thanks!

**Comment by lesaff** [comment]
FYI: For folks using PHP-FPM or FastCGI, you can safely comment out those `php_value` entries in the `.htaccess` (line 4 and 5 respectively). Copy those lines and move them to your `.user.ini` file.

Your `.user.ini` file should look like this
```
upload_max_filesize 50M
post_max_size 100M
```

**Comment by smth** [comment]
I think this is the issue I'm having. I just installed Directus via Softaculous, and I'm getting a 500 error. Log says `Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration`.

**Comment by rijkvanzanten** [comment]
See @lesaff's comment above @smth. The same applies there. 

I'll add a conditional block around these rules so it checks if php_value is supported

**Comment by smth** [comment]
OK, thanks. And the `.user.ini` file should live in the same (`public`) folder as the `.htaccess ` file in question?

**Comment by rijkvanzanten** [comment]
I believe so @smth
