### ISSUE TITLE
Error opening relational many-to-many UI

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#734]
When trying to access any items in a many-to-many UI I get the error:

http://thedirectus.com/tables/projects/388
```
Error: Uncaught TypeError: Cannot read property 'table' of undefined File: http://thedirectus.com/app/modules/tables/views/EditView.js?bust=5d27f1c1ae66206cec36fd867fe02572676fc68b Line:241
```

![screen shot 2015-03-21 at 10 45 40 am](https://cloud.githubusercontent.com/assets/522079/6765458/84af708e-cfb7-11e4-9492-06d8b13e2b19.png)

**Comment by WellingGuzman** [comment]
This was already fixed.
@benhaynes is this still happening to you?

**Comment by benhaynes** [comment]
Not getting the error any more, although it seems to not save M2M data sometimes. I'll open a specific ticket with an example.
