### ISSUE TITLE
Reload on extension page when Directus is not installed on root

### ISSUE THREAD

**Issue by timovos** [RNGR/Directus#743]
So, I've got Directus installed on /directus. Created a new extension ('example'). Extension is available in left menu. Location for extension is www.host/directus/example. When I click on the extension name in the menu, the extension works as expected (shows template). When reloading the page (refresh), I've got redirected 301 to www.host/example, which is non-existent.

**Comment by benhaynes** [comment]
Thanks @timovos – we'll look into this and get it resolved asap

**Comment by WellingGuzman** [comment]
This was fixed with #747.

@benhaynes we surely needs to find a global solutions to trailing slashes or just, keeping working that way for awhile, is not that urgent issue.

**Comment by benhaynes** [comment]
I agree, let's figure out how we want to handle trailing slashes once these last few bugs are resolved. We can use the demo server as a good reason to test use cases.
