### ISSUE TITLE
using with nginx instead of Apache

### ISSUE THREAD

**Issue by krisatkinson** [RNGR/Directus#748]
Has anyone managed to get Directus working on nginx, and if so what did you use for your server block/vhost?

**Comment by mariusz-kraj** [comment]
+1

**Comment by WellingGuzman** [comment]
@krisatkinson, @mariusz-kraj We are working on it, we'll soon added the equivalent config files for nginx.

Thanks for the concern. :+1:

**Comment by WellingGuzman** [comment]
@krisatkinson @mariusz-kraj we worked on a draft wiki where you can find here [1.2 Nginx Configuration [DRAFT]](https://github.com/RNGR/Directus/wiki/1.2-Nginx-Configuration-%5BDRAFT%5D), this would guide you to configure nginx to run Directus 6.

I'll close this ticket, if you find any issue after using the configuration that is on the wiki, do not hesitate in opening a new ticket.

Thanks!
