### ISSUE TITLE
Does not reach install screen

### ISSUE THREAD

**Issue by samtg** [RNGR/Directus#756]
Hi,  I was trying to install Directus on godaddy, and I think it meets all the requirements, from what I can tell, but I get these errors when I try to run install script:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Server Error logs:
[Fri Apr 17 17:04:50.405051 2015] [autoindex:error] [pid 28032:tid 139855166158592] [client 98.200.205.8:51650] AH01276: Cannot serve directory /home/thisdir/public_html/Directus-master/: No matching DirectoryIndex (index.html.var,index.htm,index.html,index.xhtml,index.wml,index.perl,index.pl,index.plx,index.ppl,index.cgi,index.jsp,index.js,index.jp,index.php4,index.php3,index.php,index.phtml,index.shtml,default.htm,default.html,home.htm,index.php5,Default.html,Default.htm,home.html,welcome.html) found, and server-generated directory index forbidden by Options directive
[Fri Apr 17 17:04:46.525934 2015] [autoindex:error] [pid 28032:tid 139855166158592] [client 98.200.205.8:51650] AH01276: Cannot serve directory /home/thisdir/public_html/Directus-master/: No matching DirectoryIndex (index.html.var,index.htm,index.html,index.xhtml,index.wml,index.perl,index.pl,index.plx,index.ppl,index.cgi,index.jsp,index.js,index.jp,index.php4,index.php3,index.php,index.phtml,index.shtml,default.htm,default.html,home.htm,index.php5,Default.html,Default.htm,home.html,welcome.html) found, and server-generated directory index forbidden by Options directive
[Fri Apr 17 15:56:48.787666 2015] [autoindex:error] [pid 2600:tid 139855310415616] [client 98.200.205.8:50890] AH01276: Cannot serve directory /home/thisdir/public_html/Directus-master/: No matching DirectoryIndex (index.html.var,index.htm,index.html,index.xhtml,index.wml,index.perl,index.pl,index.plx,index.ppl,index.cgi,index.jsp,index.js,index.jp,index.php4,index.php3,index.php,index.phtml,index.shtml,default.htm,default.html,home.htm,index.php5,Default.html,Default.htm,home.html,welcome.html) found, and server-generated directory index forbidden by Options directive

I would appreciate any help on this issue.

**Comment by samtg** [comment]
Hi,
     It ended up that I deleted the php_value stuff at the end of the .htaccess file, and the installation started working.  This stuff:

//# default is 64, so 64 + 72 (post_max_size value)
php_value memory_limit 136M

//# default is 8, so 8 + 64 (upload_max_filesize value)
php_value post_max_size 72M

//# default is 2
php_value upload_max_filesize 64M

//# E_ALL | E_STRICT
php_value error_reporting 32767

(slashes added here for readability)

However, when I get to the database configuration page, I can't get past it, and, even after typing in the correct database information, making sure I did, it stays on the same screen and highlights the username and password boxes:
![image](https://cloud.githubusercontent.com/assets/12001990/7216852/3d91cb8e-e5d3-11e4-811d-86ff3dc791b9.png)

Thank you for any help.

**Comment by samtg** [comment]
Okay, as it turned out, I did enter the wrong password.  Thank you.

**Comment by WellingGuzman** [comment]
Glad you install Directus correctly.

the issue with `php_value` it has been fixed in the development branch. So it would be available soon in the master branch.

Thanks.
