### ISSUE TITLE
"Choose existing files" list is missing thumb

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#769]
Go to this page:
http://thedirectus.com/tables/projects/411

If you click on "Choose Existing Thumbnails" under the *Stills* field the Files overlay comes up... but doesn't show the thumbnail. If you then click the gear in the header (don't need to change anything) and hit save... it shows up. But this problem still happens next time you try it.

Thoughts?

**Comment by WellingGuzman** [comment]
This was resolved by #772
