### ISSUE TITLE
Avoid users to upload script files

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/Directus#771]
I noticed that if there's not restriction of type of files to upload you can still upload scripts (php) and run it as it was a media file and it can do malicious effect.

So the thing is to not let users upload script and also do not let the server run scripts inside the media directory.

**Comment by benhaynes** [comment]
Good call @WellingGuzman – This setting exists on the input UI for files, but maybe it is not being enforced?

http://thedirectus.com/settings/tables/articles (then click the gear for Hero Image)

**Comment by WellingGuzman** [comment]
I know there is a setting that enforce this, but if there's nothing or it's empty it does allow the user to upload anything, and after this is not directus problem, it's the server problem, so we need to tell nginx/apache to avoid users to run scripts that exists on the media directory.

**Comment by benhaynes** [comment]
Ahh, that makes sense. Can we control those server settings? Or does the user have to implement on their server?

**Comment by WellingGuzman** [comment]
We can control those settings via htaccess and nginx config, but I still wondering if we should implement some global blacklisted files or something similar, I do not see the point one would like to upload a script to the public that can be easily runnable. or we can just use htaccess/nginx. (well nginx the user has to do it by itself on the server)

**Comment by benhaynes** [comment]
I agree – it can always default to off too. I just wonder about Directus being used for asset management, maybe some people need to manage code files?

**Comment by WellingGuzman** [comment]
PR #1026 Should do the trick now, closing this.
