### ISSUE TITLE
DIRECTUS_ENV variable in config not working

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#776]
I had someone switch this to "production" and the entire CMS stopped working. I'm not 100% sure what this is changing... but it does break things. I'll look into it more, but do you have any thoughts?

**Comment by WellingGuzman** [comment]
@benhaynes I know what's the problem, some request to the API are being called without nonce, so the API wont allow this on production environment.

I'm working on it, I just do not know the right way to implement this without forcing it.

**Comment by WellingGuzman** [comment]
This one was resolved. I'll close it.
