### ISSUE TITLE
Not able to add a new table; files missing in install

### ISSUE THREAD

**Issue by aglayamajmunic** [RNGR/Directus#794]
Hello,
I apologize as I am not a very expert developer, or if this is not the correct venue for this.
I have tried multiple times to install Directus, but have noticed that each time I install it, there are some errors. Could there be something that I am missing here?

Each time I unzip and then go through the Directus install process, the following issues arise.
- /media/ folder is missing
- config.php doesn't exist
- Composer dependencies not installed

I solved these issues by creating a media folder, the config.php, and installing Composer dependencies.
When I go into the admin and try to add a new table, I get the following message:
```
This query failed: INSERT INTO `directus_privileges` (`table_name`, `permissions`, `group_id`, `status_id`) VALUES ('Test', 'add,edit,bigedit,delete,bigdelete,alter,view,bigview', '1', NULL)
```

It looks like the `directus_privileges` table is missing the `status_id` column, but adding it doesn't seem to solve the problem, either — then when I try to create a new table in Directus, I see the new table in phpMyAdmin but it doesn't show up in the Directus user interface tables list.

I saw an earlier issue (https://github.com/RNGR/Directus/issues/720) where someone mentioned the same message, but it didn't contain any solution. 
I've checked that my system has all the requirements listed, and that my user has global admin privileges in the MySQL database. I am using OS X Yosemite 10.10.3 and MAMP 3.2.1.

Thank you in advance!

**Comment by WellingGuzman** [comment]
Hey @aglayamajmunic I already merged, development branch to master, this issue was solved weeks ago, but we haven't had merge the branch yet.

Now you shouldn't be experiencing this issue.

Thanks, I'd close it, if this happen again let us know.
