### ISSUE TITLE
Consolidate "directus_tab_privileges"

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#818]
@WellingGuzman – it seems as though the two fields in `directus_tab_privileges` are either redundant or should be moved into `directus_groups` – do you agree?

**tab_blacklist** – this is a list of sidebar "tabs" (wrong name, should be "nav_blacklist") that should be hidden from the sidebar for that user group. Technically this should be handled by the view/unlisted permission for the user_group – but this also controls the system nav items (Users, Activity, Messages, and Files) and any extensions.

**nav_override** – This only controls the Tables section (not bookmarks, extensions, or system nav items) – it should be moved to directus_groups. I just want to confirm that this doesn't control the system/extension/bookmarks sections.

_What I would recommend:_

* Move "nav_override" to `directus_groups`
* Add 4 individual columns to `directus groups` for the system nav items (`show_users`, `show_activity`, `show_messages`, and `show_files`). Each is 1 by default (shown) but can easily be hidden by turning it to 0.
* Remove the `directus_tab_privileges` table

Anyway, let's chat through this... it would be good to clean this up a bit.

**Comment by WellingGuzman** [comment]
This issue is implemented.
Would you like to review it?

**Comment by benhaynes** [comment]
If you can update the dev server with the most recent schema I'll review! Thanks @WellingGuzman

**Comment by benhaynes** [comment]
Yeehaw!
