### ISSUE TITLE
Show fallback image if file missing

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#825]
Directus should be able to fallback to a default image if a file is missing so it doesn't show the "broken image" symbol.

![screen shot 2015-06-19 at 12 20 00 pm](https://cloud.githubusercontent.com/assets/522079/8257695/94a8bb00-167d-11e5-848d-f5af54e0ece5.png)

**Comment by WellingGuzman** [comment]
Now images on files module can have a fallback to a image (which can be change a for a new one) when the images has a broken link (or perhaps is not a image).

@benhaynes what do you think on implementing this on other part, would be useful? on UI like, Single File or Multiple file for example.

**Comment by benhaynes** [comment]
@WellingGuzman I agree – I think we should implement across the framework, so we should definintely add it into the core UIs!

Thanks Welling

**Comment by benhaynes** [comment]
Thanks Welling! And I've updated this to match the design...
