### ISSUE TITLE
Commit hook to auto pull changes to dev environment

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#833]
We should have a git service hook so that whenever we commit to the dev branch it auto-pulls those changes to the hosted dev environment. This way we always have a shared/server version of the most up-to-date commits to view.

We should probably also have it pull the most recent dev (or master?) to the demo site for public users/testers.

**Comment by WellingGuzman** [comment]
@benhaynes I'm actually working on this one right now. I was thinking pulling from **development** for development server and pull from **master** for the demo site.

users/testers test Directus stable which is what **master** represents, and development is for new features, etc.

Any thoughts?

**Comment by benhaynes** [comment]
That sounds great!

**Comment by WellingGuzman** [comment]
This has been implemented on both development and demo server.
I'd close it.
