### ISSUE TITLE
User detail needs the "status/active" bar for changing

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#882]
Right now you can't adjust the status (active, inactive, deleted) of a user through the system... we need the status interface:

![screen shot 2015-07-19 at 10 35 19 pm](https://cloud.githubusercontent.com/assets/522079/8769237/9599c7b0-2e66-11e5-81fe-94976a260dad.png)

![screen shot 2015-07-19 at 10 36 30 pm](https://cloud.githubusercontent.com/assets/522079/8769239/9f92d374-2e66-11e5-8b8d-018e3c3cadbc.png)

**Comment by WellingGuzman** [comment]
@benhaynes now it's showing up the status bar above users entry, now `/users` is not filtering the status. So I'm working on that now.

**Comment by benhaynes** [comment]
Awesome, I'll take a look at this in a bit once it's wrapped up. Thanks!!

**Comment by WellingGuzman** [comment]
@benhaynes Do you know why the user status is hard-coded to be always active here in [EntriesCollection.js](https://github.com/RNGR/Directus/blob/development/app/core/entries/EntriesCollection.js#L66-L71)?

**Comment by WellingGuzman** [comment]
This is why the filter doesn't work. and it always keep showing all the active users.

**Comment by benhaynes** [comment]
@WellingGuzman Maybe because there was no dropdown to select the status type and it needed to show active? I'd say if we add in the filter we should be ok to adjust this.

**Comment by WellingGuzman** [comment]
@benhaynes ok, cool, so I'm going to remove those line, so the dropdown works.

**Comment by benhaynes** [comment]
@WellingGuzman Awesome! The only thing is that if you make a user inactive or deleted it should log them out next time the server is polled. Currently it let's them navigate around (and see data) or shows an error from getAvatar()... or an empty/gray page when they refresh the page. 

Can we have it log them out? Maybe with an alert like this (similar to inactive logout):

![screen shot 2015-08-04 at 11 22 44 am](https://cloud.githubusercontent.com/assets/522079/9064576/31a29cc8-3a9b-11e5-901c-5d21dd26acd8.png)


Also, it seems that "Nothing to see here" is showing up even with active users:

![screen shot 2015-08-04 at 11 25 07 am](https://cloud.githubusercontent.com/assets/522079/9064647/8b49934e-3a9b-11e5-8436-0eca64c0a700.png)

Lastly, could we have inactive users show up in a group labeled "Inactive" at the end and make them **opacity:0.4**?

![screen shot 2015-08-04 at 11 29 02 am](https://cloud.githubusercontent.com/assets/522079/9064772/0df3c09e-3a9c-11e5-8e56-5eaf3ef826d1.png)

**Comment by benhaynes** [comment]
@WellingGuzman Looking great!! A few small fixes:

Could the "Inactive" group always be last on the users page?
Is there a way to logout users (who are logged in) when their account is made inactive/deleted?

**Comment by WellingGuzman** [comment]
> Could the "Inactive" group always be last on the users page?
I made it to be last on the users page. but I wonder how did you manage to to be other but last?

> Is there a way to logout users (who are logged in) when their account is made inactive/deleted?
I was trying to sort something out here, but I couldn't without us managing session into the database, we need to have all the sessions belonging to a user in a place we can easily manage, all the session by default are stored as a file and serialized in a different way that php serialize object.

We must implement a table that would store the sessions, or do have another solutions? I'd look if we have more options here.

**Comment by benhaynes** [comment]
@WellingGuzman 
For the auto-logout... once the user refreshes the page they lose their ability to see private data. Is it possible to check if the current user is active with each API/page request and force refresh them if they are inactive? Or redirect them to the /logout page?

**Comment by benhaynes** [comment]
I'll call this a new feature... we can implement in the next version.
