### ISSUE TITLE
Can't add Avatar file (Image) to an user

### ISSUE THREAD

**Issue by WellingGuzman** [RNGR/Directus#884]
An Image can't be set to an user using the file UI.

You can pick the image and display the preview, but as soon as it saved, the image is not saved it.

**Comment by benhaynes** [comment]
Do I need to adjust anything on my local machine? I am using the most recent commit... but maybe there was a schema change?

![screen shot 2015-08-04 at 11 39 17 am](https://cloud.githubusercontent.com/assets/522079/9065057/9a9a7cb2-3a9d-11e5-98fb-121e73f3efec.png)

And then if I refresh:

![screen shot 2015-08-04 at 11 39 43 am](https://cloud.githubusercontent.com/assets/522079/9065063/a01af3a6-3a9d-11e5-810a-89311111a499.png)

**Comment by WellingGuzman** [comment]
There was a change in the setting name record. now there's not `file_file_naming` now it's named `file_naming`.

try using this:
```sql
update directus_settings SET name = 'file_naming' WHERE name = 'file_file_naming';
```

**Comment by WellingGuzman** [comment]
I tried on the demo site and it was fixed with this, I get the first error, but I didn't get the error after refreshing the page.

**Comment by benhaynes** [comment]
That seems to be fixed... but my uploads are not working. I'll add a separate ticket to figure that out though. Thanks!!
