### ISSUE TITLE
Update Settings > Files options

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#890]
We should remove the "File Title Naming" option... it should **always be the file name**, not the ID. 

**The first option should just be called: "File Naming"... not "File File Naming"**

Also, it would be nice to add a "random hash" option for file naming... that uses an md5 of the datetime (or some other random/unique naming).

![screen shot 2015-07-20 at 11 35 42 am](https://cloud.githubusercontent.com/assets/522079/8779868/98aea476-2ed3-11e5-8817-775c3c1ecbeb.png)

**Comment by WellingGuzman** [comment]
@benhaynes now `file_file_naming` is `file_naming` and there's not more `file_title_naming`. and did some fixes in the way, and I implemented the hash name option.

Need a bit of refactor and cleaning, but I get it to work.

**Comment by WellingGuzman** [comment]
I'll close this by now. refactor would be another chapter. what do you think @benhaynes ?

**Comment by benhaynes** [comment]
@WellingGuzman – Yes, I agree!
