### ISSUE TITLE
Directus "Help text" alert system

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#892]
I think we need a system for adding "help" information to certain terms/areas of the framework. I imagine it working like this:

Any elements with a class of "toggle-help-text" and a data attribute of "data-help-text" would open a Directus alert with the data attributes text and an OK button (no cancel). I can give those elements a help cursor so users know they can click on them.

With this in place, I can quickly add help text throughout the system (see image below) to explain things in context.

![screen shot 2015-07-20 at 11 56 39 am](https://cloud.githubusercontent.com/assets/522079/8780448/fa7a3924-2ed6-11e5-90d0-05bf28e377f1.png)

**Comment by WellingGuzman** [comment]
@benhaynes This is a small implementation but it does the trick, it open a modal alert when any element with  class `toggle-help-text` gets a click.

I;d close this. we can reopen if it still need some more work or ideas directly to how it should work.

**Comment by benhaynes** [comment]
Perfect!
