### ISSUE TITLE
Error deleting item (with permission)

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#893]
I am trying to delete an item (local server) and am getting a permission error:

```
Restricted Access
You don't have permission to access this table. Please send this to IT:
{ "message":"[Group #1 User #2] BigHardDelete\/HardDelete access forbidden on table 'offices'." }
```

But checking the permissions, my group has **"allow_delete" = "2"** for that table – not sure why I can't delete. Thoughts @WellingGuzman ?

**Comment by WellingGuzman** [comment]
You are trying to **harddelete/bigharddelete** a item, which **"allow_delete" = "3" / allow_delete" = "4"**.
But it should fallback to _update_ the status column if it has status column. If you are using the same *offfices* table that I'm using it does have status column. I'd take a look, because it should update the item instead of delete it.

**Comment by benhaynes** [comment]
@WellingGuzman – Ahh, so is it like this:

* 0: You can't delete
* 1: You can soft-delete your own (delete)
* 2: You can soft-delete anyones (big-delete)
* 3: You can delete your own (hard-delete)
* 4: You can delete anyones (big-hard-delete)

I couldn't remember if we were only using 0,1,2 and the hard was determined by the existence of a status field or not.

If that's the case, should we make the default delete permission "4"? And yes, I agree that it should fallback on update (soft) if you have hard-delete permissions but there's no status column.

Meaning, if you have `allow_delete=4` with an active column... you should still be able to soft delete items. Just not the other way around.

**Comment by WellingGuzman** [comment]
@benhaynes well, you are right we can say if it's hard or soft delete based on the existence of a status column.

> Meaning, if you have allow_delete=4 with an active column... you should still be able to soft delete items. Just not the other way around.

In that case, should we NEVER harddelete on the existence of status column even though we had harddelete?, so we don't need to use **3** and **4**.

And was you said we should determine that by whether or not there's a status column.

**Comment by benhaynes** [comment]
@WellingGuzman Perfect – I think this is a bit easier to understand, especially when saving permissions. So we'll remove 3/4 from `allow_delete` and use the existence of the status column to differentiate.

I like it!

**Comment by WellingGuzman** [comment]
@benhaynes perfect, so that how is going to be.

Should we open a new ticket for it, or just keep this open for it?

**Comment by benhaynes** [comment]
@WellingGuzman – We can use this ticket since it has the comments...

**Comment by benhaynes** [comment]
Hey @WellingGuzman – what is the status of the 3/4 states being removed?

**Comment by WellingGuzman** [comment]
This was implemented. so I'd close the issue. if we find something, we'll reopen it.

**Comment by benhaynes** [comment]
@WellingGuzman Again, looking good! But I'm having an issue with **delete=1** (only delete yours) with the following setup:

* I added "user_created" to Table A
* I added my user ID to that column for only one record within Table A
* I added "user_created" to "user_create_column" under directus_tables for Table A
* I set the Table A permissions to allow_delete=1
* I tested and **it allows me to delete any items**

Any thoughts? Am I setting up the user_create_column incorrectly? Maybe we should show some sort of warning on the permissions page if they don't have the user_create_column setup with a column?

![screen shot 2015-08-04 at 11 11 21 am](https://cloud.githubusercontent.com/assets/522079/9064281/c43e1988-3a99-11e5-806a-cf2305baf437.png)


**"Can Delete Their Items" could say:**
"Can delete their items: `user_created`"
or...
"Can delete their items: no column chosen"

**Comment by WellingGuzman** [comment]
You can review this commits now, I added the column name next to **Can Delete Their Items**.
And also you can't delete items that are not yours when delete=1 is set.

**Comment by benhaynes** [comment]
@WellingGuzman I see the column name under permissions:

![screen shot 2015-08-17 at 11 50 51 am](https://cloud.githubusercontent.com/assets/522079/9309239/4209e108-44d6-11e5-8727-16946c942058.png)

But I can still delete items that are mine, another user, or NULL... I should only be able to delete items that are mine though. I am testing this from the listing page and detail page... and this is a soft-delete table.

Thoughts?

**Comment by WellingGuzman** [comment]
@benhaynes this and #921 is happening to you, but not to me, I tried again, and I can't delete items that are not mine when **allow_delete=1**.

I'm going to test a bit more to check if I keep getting the expected results or the issue you get.

**Comment by benhaynes** [comment]
I will try to get it happening on the dev server today/tonight so we're looking at the same thing.

**Comment by benhaynes** [comment]
@WellingGuzman – OK, I have the dev server setup to showcase the issue:

The administrator permissions for the offices table are delete=1 (only delete yours)
The user_create_column for directus_tables:offices is set to user_created

Go to...
http://thedirectus.com/tables/offices

And  you can delete any items (the one created by Justin and all NULLs).

Is this because Admins have special/all abilities? If so, then we need to remove the privileges/permissions area for them.

**Comment by WellingGuzman** [comment]
@benhaynes I found the issue on soft delete it wasn't checking for `delete` permission but for `edit` before performing update.

Take a look, I went to http://thedirectus.com/tables/offices and everything it's working properly.

**Comment by benhaynes** [comment]
Looks good!
