### ISSUE TITLE
Moving "Add Bookmark" button to sidebar

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#894]
Right now, you can only add listing pages as bookmarks, and the "add" icon is taking up room in the header. I think we should move it into the sidebar so the Bookmarks section is always visible, and the add button is there. This would allow uses to bookmark ANY page – and centralizes the location of that component.

![screen shot 2015-07-20 at 3 38 18 pm](https://cloud.githubusercontent.com/assets/522079/8785456/b652e722-2ef5-11e5-9f6f-1f93f7ae5440.png)

**Comment by benhaynes** [comment]
@WellingGuzman – I'm getting a few errors doing different things:

**Not sure what caused this one:**
```
Server Error
set() expects an array of values
```

_Some things I noticed:_
* It goes to the bookmark URL but immediately changes to this: http://thedirectus.com/tables/offices
* I noticed that within `directus_bookmarks` some URLs have a leading slash and others don't
* I can't tell where it saves the filters you have on when bookmarking (`directus_preferences`?)
* It doesn't seem to save the active state for listing pages (View All, Active, Draft, etc) under `directus_bookmarks>active`
* I added a bookmark called "Offices?" and I think the URL needs to either encode the char or we should probably regex the chars allowed in the Bookmark name


_What it's supposed to save when you create a bookmark:_
* Page (this is all it needs unless it's a listing page)
* Statuses being viewed (all, active, draft, etc)
* All filters
* Visible columns
* Sorted column
* Column sort direction

**Comment by benhaynes** [comment]
Also, we need to keep the Bookmark group in the sidebar even if there are no Bookmarks... otherwise no one will be able to add them. ;)

I can make this adjustment if you want... it's easy enough to remove an "if" statement.

**Comment by WellingGuzman** [comment]
@benhaynes you right haha, didn't notice that. go ahead if you like, otherwise I'd do it.

In that case, I knew something was wrong with bookmarks, because I don't remember it working that way.

Does it work that way before?

> I noticed that within directus_bookmarks some URLs have a leading slash and others don't
Yup was my fault, but I fixed.

**Comment by benhaynes** [comment]
@WellingGuzman – I'll test now, thanks! I remember the bookmarks working before, but I hadn't thoroughly tested it in a few months so I could be wrong. I'll see what issues there are now...

**Comment by WellingGuzman** [comment]
@benhaynes What I'm certainly sure is that it used to save the search query, but now it's not working. I'd check that out.

**Comment by benhaynes** [comment]
It seems that creating a bookmark is partially working, but it seems to be saving incorrectly. It seems like it's saving the previous state of the page. For instance: If I create bookmark A, then bookmark B... then clicking A takes me to B, and clicking B takes me to where I went after saving B. Very confusing, I know!

Could you take a look to see why these aren't going to the correct filters when clicked, @WellingGuzman ?

**Comment by WellingGuzman** [comment]
I'd close this one, preferences are being saved correctly. otherwise we'll reopen it.

**Comment by benhaynes** [comment]
@WellingGuzman – This is working MUCH better... here are the only two issues I can see now:

*Save Status*
The bookmark is not saving the status state (in the dropdown in the header) of "View All", "View Active", "View Inactive". So if you save a bookmark with ACTIVE and then go to INACTIVE... when you click on the bookmark it should take you back to ACTIVE.

*Not Navigating After One Click*
When I click on a bookmark, it works as expected... but then if I change the sort and filter and click the bookmark again it no longer updates the page. I see the URL flicker, but it doesn't update the parameters again. Everytime you click the bookmark it should take you to that page with the saved parameters.

*BONUS*
Is there anyway to highlight the bookmark in the sidebar when you are viewing it? I know this is probably complex since it's hard to know when you're viewing a bookmark versus a table.

**Comment by WellingGuzman** [comment]
_Save Status_
When you save a bookmark with ACTIVE and then change it to INACTIVE (this INACTIVE is changed automatically to the actual table), then if you go back to the bookmark it would show you ACTIVE, and then if you go to the bookmark "original table" it would be INACTIVE.

_Not Navigating After One Click_
Now every time you click a bookmark it should show you its actual state (preferences).

_BONUS_
Now  you can see which bookmark you are seeing (highlighted), but as soon as you change a preference it would change the highlight to the table. (kind of good, because after you change any preferences those preferences are sent directly to the table and not the bookmark)


**Note:** There're some issues creating or retrieving bookmark for any other pages that are not tables.

**Comment by benhaynes** [comment]
Every once in a while I do something that NULL-ifies some of the `directus_preferences` fields. I'm not sure what's causing it... and I can't replicate now. I will close this and open a new ticket if I can figure out what the cause is.

Thanks Welling... especially for the bonus!

**Comment by WellingGuzman** [comment]
@benhaynes haven't happened to me yet, but I'd work on it as soon as you find a way to replicate it. :+1:
