### ISSUE TITLE
Getting "Server Error" when sending a new message

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#921]
Not sure why, but trying to send a dummy message and am getting a Server Error with no other message:

![screen shot 2015-08-04 at 11 35 11 am](https://cloud.githubusercontent.com/assets/522079/9064962/0204717e-3a9d-11e5-91c3-06b465853b04.png)

**Comment by benhaynes** [comment]
Also, it seems that it does send the message though:

![screen shot 2015-08-04 at 11 37 01 am](https://cloud.githubusercontent.com/assets/522079/9064990/2da1a8d8-3a9d-11e5-9997-046e95ac9d81.png)

**Comment by WellingGuzman** [comment]
Hmm, Let me see what is happening here, because I can send message with no problem.

Can you check the developer tools and see what error throw the http request? (screenshot)

**Comment by benhaynes** [comment]
Sure, here ya go:

![screen shot 2015-08-05 at 11 07 08 am](https://cloud.githubusercontent.com/assets/522079/9089255/374b766e-3b62-11e5-9e32-2d0178e07c90.png)

**Comment by WellingGuzman** [comment]
@benhaynes Can you also send me the screenshot of the http request in red "rows/" (the first one) response content.

Thanks!

**Comment by benhaynes** [comment]
@WellingGuzman Sure, but they appear empty!

![screen shot 2015-08-06 at 11 55 50 am](https://cloud.githubusercontent.com/assets/522079/9116415/4013e936-3c32-11e5-8a42-a1f04f7b6822.png)



![screen shot 2015-08-06 at 11 56 33 am](https://cloud.githubusercontent.com/assets/522079/9116419/44a73a34-3c32-11e5-993b-36e82a2f7749.png)

**Comment by WellingGuzman** [comment]
@benhaynes do you still keep getting this error?

**Comment by benhaynes** [comment]
Yes, still getting it. I got a different error on the dev server (mail not set up it seems). Thoughts?

![screen shot 2015-08-24 at 4 37 11 pm](https://cloud.githubusercontent.com/assets/522079/9451751/7c909a94-4a7e-11e5-8e8d-f6fbb7595413.png)

**Comment by WellingGuzman** [comment]
@benhaynes I installed PHPMailer, and tried it again and now it's working.

Now, can you update composer and the schema? maybe there's a db change missing in your end.

**Comment by benhaynes** [comment]
@WellingGuzman Sure, I'll check/update this when I get home. Is it possible to throw a Directus alert if email is not set up properly? Something like:

"Your server doesn't seem to be properly set up to send emails – please contact your Administrators."

**Comment by benhaynes** [comment]
Looks good!
