### ISSUE TITLE
Escape Bookmark titles in URLs

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#931]
Certain bookmark titles break the URL since it's not escaped. For instance, the slash in the following breaks the bookmark:

**"Active 8/5"**
http://local.directus.com:8888/tables/offices/pref/active%208/5

We need to escape these titles when they are URLs.

**Comment by WellingGuzman** [comment]
In fact we need to escape even more datas, if I create a table and name it **"Active 8/5"**, it would create the table, but I  can't access to it.

I'd work on it.

**Comment by WellingGuzman** [comment]
@benhaynes **NOTE:** Something to keep in mind is that I don't know yet if it is a Directus or Zend DB bug, but querying the rows of an table named "Active 8/5" would throw an error like this:

![screen shot 2015-08-12 at 11 14 24 pm](https://cloud.githubusercontent.com/assets/1531291/9241890/90f7c632-4147-11e5-9094-258f7e02ae48.png)

Notice the name of the table after WHERE: 
```
`Active` `8``/``5`
```

**Comment by benhaynes** [comment]
In my example, "Active 8/5" was just a bookmark name, not a table name. The table for that issue was actually "offices". I don't think you can/should create tables or fields with slashes or spaces. @wellingguzman

**Comment by WellingGuzman** [comment]
@benhaynes yeah I know, that what I meant when I say we need to escape more data, right now you can create a table with slashes and spaces. but it would throw and error, but if you check the database the tables are there. it returns an error trying to get data for that table.

Now, what should we do here? sanitize everything, so "Active 8/5" will sanitize to "Active-8-5"?

What do you think? or better yet, warn that the table can't have symbols just alphanumerics.

**Comment by WellingGuzman** [comment]
Also In order to the slashes encoded to work, it needs add `AllowEncodedSlashes NoDecode` on the apache config file, otherwise it would keep the same error as if it weren't encoded.

**Comment by benhaynes** [comment]
@wellingguzman Ahh, I see. 

I would say we warn the user that the table/field name is not valid using a regex check. And reformat the input value to be formatted correctly... but don't auto submit it. Let them have a chance to change it to something else.

**Comment by WellingGuzman** [comment]
@benhaynes yeah, I think the warning is better.

Also users can create table directly on the database with spaces, slashes and specials characters.

We need to at least find a way to wrap this tables names so Directus don't throw an error about malformed tables name.

**Comment by WellingGuzman** [comment]
I'll close this, bookmarks are now escaped. (also the tables)
