### ISSUE TITLE
DB user password may empty

### ISSUE THREAD

**Issue by jomonkj** [RNGR/Directus#974]
avoid password empty validation

**Comment by WellingGuzman** [comment]
@jomonkj can you provide more information regarding this issue?

**Comment by jomonkj** [comment]
When installing Directus on my local environment. Asking me to enter password for db user. I am using root as username and password as empty. I think most of peoples follow this default.
so password field not mandatory.

**Comment by WellingGuzman** [comment]
@jomonkj you're right, I understand the issue now. Thanks!
