### ISSUE TITLE
mCrypt is not optional

### ISSUE THREAD

**Issue by LouisGac** [RNGR/Directus#991]
Hi, 

not really a bug, but you wrote everywhere in your doc that mcrypt is optional, and it is not.  
slim/slim 2.3.2 is required by composer, Directus doesn't install without slim/slim 2.3.2, but slim/slim 2.3.2 required ext-mcrypt.

So, I think that mcrypt is required. 

++

**Comment by benhaynes** [comment]
Ahh, a very good point! I'll adjust the docs/marketing site now. Thanks for the heads up!

**Comment by benhaynes** [comment]
Added to readme, marketing site, and wiki pages
