### ISSUE TITLE
server error at login after fresh installation

### ISSUE THREAD

**Issue by Pawnerd** [RNGR/Directus#992]
After a fresh installation of Directus, the login page shows the following error message after each login attempt: "Server error occurred!". [Screendump](http://puu.sh/jW3M0/3cdea65b67.png)

In Apache I read the following error:

File does not exist: /var/domains/somesite.com/public_html/api/1, referer: http://somesite.com:6070/login.php

Operating system is Debian Wheezy (7) and I am using Apache2 with PHP >= 5.6 with mod_rewrite installed. I should notice the application is not running on default port 80, instead it uses port 6070.

**Comment by Pawnerd** [comment]
Great news, I found the cause of this issue. It had to do with apache configuration. Normally I run my webservices in Nginx and I completely screwed up in the virtualhosts file for this webapplication.

In case you have the same error type as me, this means there is some issue with mod_rewrite. I suggest you read #721.

**Comment by benhaynes** [comment]
Ahh, great to hear you found the problem @Pawnerd – can you think of a way to warn users of this through the docs or framework directly? I wonder if the code can identify when this happens and help the user understand/resolve things so they don't have to search for a solution.

**Comment by Pawnerd** [comment]
A proper warning would be that If mod_rewrite is enabled but the main api file is not accessable (404 error state), it means that:
- not all files are uploaded
*- somebody made the same misstake as me by missconfiguring Apache2.*

**Comment by benhaynes** [comment]
I like it – I'll open a new ticket to add that alert in! And thanks for the Wiki update...
