### ISSUE TITLE
Not permitted adding column to table

### ISSUE THREAD

**Issue by ConnorGBrewster** [RNGR/Directus#998]
I am using Directus in Vagrant, I've used my own setup on the vagrant setup from the wiki, but I still run into this same problem. The mysql user does has all the proper permissions to alter tables.

![screen shot 2015-09-01 at 9 10 40 pm](https://cloud.githubusercontent.com/assets/9086315/9622278/19a6766c-50ee-11e5-9426-50277c735588.png)

**Comment by ConnorGBrewster** [comment]
I have found that it is due to the allow_alter value on the table entry on the directus_privileges table is set to 0, it set to 0 by default and I can not seem to adjust through the web interface. Also why is it set to 0 by default?

**Comment by WellingGuzman** [comment]
@ConnorGBrewster what I found odd is that the table `allow_alter` was set with 0.
Although we decided to be 0 by default as by default you don't have any permission to a table to prevent a undesired permission to a group.

Now you are right there's not way to adjust `allow_alter`. I'd work on that, also I'd check why the table you created didn't have all the permissions set.

Thanks

**Comment by benhaynes** [comment]
@WellingGuzman should we add `alter` to the Settings>Permissions page? Or is this more an issue of default values?

**Comment by ConnorGBrewster** [comment]
@benhaynes I feel that the user who creates the table should by default be able to alter it. It would be a pain to create a table and then have to go back to permissions to grant myself alter privileges and then go back to be able to add columns.

**Comment by benhaynes** [comment]
@ConnorGBrewster @WellingGuzman 
I agree with that – but also wonder about which groups should have this permission. Admin groups are the only ones who should be able to `alter` tables... I know previously we had that permission baked-into that group, but now we're thinking an "admin" boolean on each of the directus_groups might be better.

The question is, can anyone think of a reason why a non-admin group would need an `alter` command?

**Comment by ConnorGBrewster** [comment]
@WellingGuzman @benhaynes I think that if you have the permission to to create a table, you should have permission to alter the table. Wouldn't really make sense to be able to create a table and be able to actually add columns. Maybe when you create a table you automatically have permission to all actions on that table and then you can give access to groups and other people while you create the table. And then have the admin group that has rights on everything.

**Comment by WellingGuzman** [comment]
> I feel that the user who creates the table should by default be able to alter it.

You're right, this is a bug, if you are able to create it, you must have the permission to alter it. that's how it used to work.

**Comment by WellingGuzman** [comment]
But again, those are two separate permission, as normally if you are using admin, you can do both by default that's my concern. so I think, alter would turn into the permission that would say whether or not you can create tables and columns, I'd think it would be much better than check for the `group_id`, which is how we check if it's admin or not.

Thoughts?

**Comment by ConnorGBrewster** [comment]
@WellingGuzman I agree, although the  ```alter``` permission should still be on a per table basis. You might have permission to create tables; however, there may be certain tables that you have no permission to  ```alter```. I think the best option would be have group permissions and user permissions. If you create a table, you are the only user with ```alter``` permissions and the admin group automatically has all privileges on all tables. From there you can adjust privileges on a per user or per group basis.
What do you guys think?

**Comment by WellingGuzman** [comment]
@ConnorGBrewster I missed that point, you're right, `alter` are per table permission, so we shouldn't depend on that to know whether a group can create a table or not. so we were talking about adding a group field `is_admin` by now, so this would be our quickest solutions without altering too much how the permissions works.

Thanks for all your comments. :+1: :100:

**Comment by ConnorGBrewster** [comment]
@WellingGuzman No problem! Glad to help out!

**Comment by ConnorGBrewster** [comment]
@WellingGuzman Looks like I have found part of the issue. [Alter Permission Issue Gist](https://gist.github.com/ConnorGBrewster/b11b9efaea8035da60b1)

**Comment by WellingGuzman** [comment]
@ConnorGBrewster Good catch! Thanks a lot. That's the problem right there, we were trying to make sure only admin users gets `alter` permission, so if a non-admin user try to add an `alter` permission we make sure it's set to 0.

Changing this:
```php
private function verifyPrivilege($attributes) {
    // Making sure alter is set for admin only.
    if($this->isCurrentUserAdmin() && !array_key_exists('allow_alter', $attributes)) {
        $attributes['allow_alter'] = 1;
    } else {
        $attributes['allow_alter'] = 0;
    }

    return $attributes;
}
```

To this:
```php
private function verifyPrivilege($attributes) {
    // Making sure alter is set for admin only.
    if(!$this->isCurrentUserAdmin() && array_key_exists('allow_alter', $attributes)) {
        $attributes['allow_alter'] = 0;
    }

    return $attributes;
}
```

would solve the problem.

**Comment by WellingGuzman** [comment]
Or better yet.
```php
    private function verifyPrivilege($attributes) {
        // Making sure alter is set for admin only.
        if(array_key_exists('allow_alter', $attributes)) {
            if ($this->isCurrentUserAdmin()) {
                $attributes['allow_alter'] = 1;
            } else {
                $attributes['allow_alter'] = 0;
            }
        }

        return $attributes;
    }
```

**Comment by ConnorGBrewster** [comment]
@WellingGuzman looks like a good temp fix. In what cases is the verifyPrivilege function called?

**Comment by WellingGuzman** [comment]
@ConnorGBrewster it's called inside `insertPrivilege` and `updatePrivilege` methods.

Here [DirectusPrivilegesTableGateway.php#L76](https://github.com/WellingGuzman/directus6/blob/master/api/core/Directus/Db/TableGateway/DirectusPrivilegesTableGateway.php#L76) and Here [DirectusPrivilegesTableGateway.php#L98](https://github.com/WellingGuzman/directus6/blob/master/api/core/Directus/Db/TableGateway/DirectusPrivilegesTableGateway.php#L98)
