### ISSUE TITLE
Ignore .DS_Store in build?

### ISSUE THREAD

**Issue by wzyboy** [RNGR/Directus#999]
Hi,

currently the [build branch](https://github.com/RNGR/Directus/tree/build) contains some `.DS_Store` files. Should these files be excluded when building?

**Comment by WellingGuzman** [comment]
@wzyboy oh got catch, thanks you are right!

**Comment by WellingGuzman** [comment]
@wzyboy it should be fixed by now. rebuilding and pushing.
I'll close this.
